Automated import of avbuild 0.8.0

diff --git a/avbuild b/avbuild
--- a/avbuild
+++ b/avbuild
@@ -1,6 +1,10 @@
 #!/bin/bash
 # av-build - download and build audio/video command line tools
 #
+# Version 0.8.0 (2015-02-26)
+# Apply datetime stamp to build directory instead of base. Add directory empty check.
+# Re-download invalid source files. Improve usage and progress displays, error handling.
+#
 # Version 0.7.0 (2015-02-26)
 # Add autotools, opus, and speex. Use xz compressed sources where possible.
 #
@@ -26,7 +30,7 @@
 
 av-build() {
 
-    VERSION="av-build 0.7.0"
+    VERSION="av-build 0.8.0"
     SOURCE_URLS=('http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.xz' \
                  'http://ftp.gnu.org/gnu/automake/automake-1.15.tar.xz' \
                  'http://ftp.gnu.org/gnu/libtool/libtool-2.4.6.tar.xz' \
@@ -53,17 +57,18 @@ av-build() {
     # Internal vars
     SELF="${BASH_SOURCE[0]}"
     SELF_NAME=$(basename "${SELF}")
+    CREL=$(echo -e "\r"$(tput el))
     DATETIME=$(date +%Y-%m-%d-%H%M%S)
     HELP="\
 usage: $SELF_NAME [-hv]
-       $SELF_NAME [-dfls] [directory]
+       $SELF_NAME [-dfls] [target_dir]
 where:
    -h  display this help text
    -v  display version information
-   -d  force redownload existing source files
+   -d  force re-download existing source files
    -f  force overwrite existing directory
    -l  list sources (do not build)
-   -s  append date/time stamp to directory"
+   -s  append datetime stamp to target_dir/build"
 
     # Arguments
     DOWNLOAD=false
@@ -84,7 +89,7 @@ where:
             return 0
             ;;
         d)
-            # Force redownload existing source files
+            # Force re-download existing source files
             DOWNLOAD=true
             ;;
         f)
@@ -96,7 +101,7 @@ where:
             LIST=true
             ;;
         s)
-            # Append date to build directory
+            # Append datetime to build directory
             STAMP=true
             ;;
         \?)
@@ -144,23 +149,21 @@ where:
         else
             BASE_DIR="av-build"
         fi
-        if [[ ${STAMP} == true ]]; then
-            BASE_DIR="${BASE_DIR}_${DATETIME}"
-        fi
-        if [[ ${FORCE} != true ]] && [[ -e ${BASE_DIR} ]]; then
-            echo "${SELF_NAME}: directory exists: ${BASE_DIR}" >&2
+        if [[ ${FORCE} != true ]] && [[ -e ${BASE_DIR} ]] && [[ $(ls -A ${BASE_DIR} | grep -v '^\.') ]]; then
+            echo "${SELF_NAME}: directory exists and is not empty: ${BASE_DIR}" >&2
             return 1
         elif ! mkdir -p "${BASE_DIR}" >/dev/null 2>&1; then
             echo "${SELF_NAME}: unable to create directory: ${BASE_DIR}" >&2
             return 1
         fi
-        echo -n "Creating destination..."
         BASE_DIR=$(cd "${BASE_DIR}" && pwd)
-        echo " done."
 
         # Set up environment
         DOWNLOAD_DIR="${BASE_DIR}/download"
         BUILD_DIR="${BASE_DIR}/build"
+        if [[ ${STAMP} == true ]]; then
+            BUILD_DIR="${BUILD_DIR}_${DATETIME}"
+        fi
         SOURCE_DIR="${BUILD_DIR}/source"
         if [[ ${FORCE} == true ]] && [[ -e ${BUILD_DIR} ]]; then
             rm -rf ${BUILD_DIR}
@@ -237,44 +240,45 @@ where:
         done
 
         # Download
-        echo -n "Downloading sources..."
         cd ${DOWNLOAD_DIR}
-        ERROR_MSG=""
+        ERRORS=()
         for INDEX in "${!SOURCE_URLS[@]}"; do
-            if [[ ${DOWNLOAD} == true ]] || [[ ! -e "${SOURCE_FILES[INDEX]}" ]]; then
+            echo -en "${CREL}"
+            printf "Downloading [%02i/%02i] %s" "$((${INDEX}+1))" "${#SOURCE_URLS[@]}" "${SOURCE_FILES[INDEX]}"
+            if [[ ${DOWNLOAD} == true ]] || [[ ! -e "${SOURCE_FILES[INDEX]}" ]] || ! tar -tf "${SOURCE_FILES[INDEX]}" >/dev/null 2>&1; then
                 if ! curl -Ls "${SOURCE_URLS[INDEX]}" -o "${SOURCE_FILES[INDEX]}" 2>/dev/null; then
-                    ERROR_MSG="${ERROR_MSG}${SELF_NAME}: unable to download source: ${SOURCE_URLS[INDEX]}\n"
+                    ERRORS+=("${SOURCE_URLS[INDEX]}")
+                    echo -en " [FAIL]\n"
                 fi
             fi
         done
-        if [[ "${ERROR_MSG}" != "" ]]; then
-            echo " failed."
-            echo -en "${ERROR_MSG}" >&2
+        echo -en "${CREL}"
+        if [[ ${#ERRORS[@]} -gt 0 ]]; then
+            echo -e "${SELF_NAME}: unable to download: ${ERRORS[*]}" >&2
             return 1
         fi
-        echo " done."
+        printf "Downloading [%02i/%02i] complete.\n" "$((${INDEX}+1))" "${#SOURCE_URLS[@]}"
 
         # Build
-        echo "Building..."
         for INDEX in "${!SOURCE_NAMES[@]}"; do
-            echo -n "- ${SOURCE_HUMAN[INDEX]}"
+            echo -en "${CREL}"
+            printf "Building    [%02i/%02i] %s" "$((${INDEX}+1))" "${#SOURCE_NAMES[@]}" "${SOURCE_HUMAN[INDEX]}"
             if [[ "${SOURCE_COMMANDS[INDEX]}" != "" ]]; then
                 COMMANDS=()
                 IFS=';' read -a COMMANDS <<< "${SOURCE_COMMANDS[INDEX]}"
                 for C in "${COMMANDS[@]}"; do
-                    #if eval $(echo -e "${C}"); then
                     if eval $(echo -e "${C}") >/dev/null 2>&1; then
                         continue
                     else
-                        echo " (fail)"
-                        echo "${SELF_NAME}: unable to build source: ${SOURCE_NAMES[INDEX]}" >&2
+                        echo -en " [FAIL]\n"
+                        echo -e "${SELF_NAME}: unable to build: ${SOURCE_HUMAN[INDEX]}" >&2
                         return 1
                     fi
                 done
             fi
-            echo " (pass)"
         done
-        echo "Build complete."
+        echo -en "${CREL}"
+        printf "Building    [%02i/%02i] complete.\n" "$((${INDEX}+1))" "${#SOURCE_HUMAN[@]}"
 
     fi
 
